/**
 * Milestones Data for Chinmaya Mission Adoni Journey
 * Chronological record of key events, temples, youth activities and cultural milestones.
 */

export const MILESTONES_DATA = [
  {
    id: 1,
    year: '1992',
    displayYear: '1992',
    title: 'Chinmaya Mission Adoni Established',
    description: 'Chinmaya Mission, Adoni, was established.',
    type: 'foundation',
    tag: 'Foundation Stop',
    km: 'KM 01',
    icon: 'Sparkles',
  },
  {
    id: 2,
    year: '1993 onwards',
    displayYear: '1993 → 2026',
    title: 'Chinmaya Geeta Chanting Competitions',
    description: 'Chinmaya Geeta Chanting Competitions have been conducted from 1993 onwards, continuing through 2026.',
    type: 'continuing',
    tag: 'Continuing Tradition',
    isContinuing: true,
    km: 'KM 02',
    icon: 'BookOpen',
  },
  {
    id: 3,
    year: '1995',
    displayYear: '1995',
    title: 'Andhra Pradesh CHYK Camp',
    description: 'Andhra Pradesh CHYK camp was organised. Awarded BEST UPCOMING CENTER.',
    highlightBadge: 'BEST UPCOMING CENTER',
    type: 'award',
    tag: 'Youth Camp & Award',
    km: 'KM 03',
    icon: 'Award',
  },
  {
    id: 4,
    year: '1996',
    displayYear: '1996',
    title: 'Sri Shantamalleswara Swamy Temple',
    description: 'Development of Sri Shantamalleswara Swamy Temple is recorded.',
    type: 'temple',
    tag: 'Temple Development',
    km: 'KM 04',
    icon: 'Landmark',
  },
  {
    id: 5,
    year: '2001',
    displayYear: '2001',
    title: 'Chinmaya Cultural Complex',
    description: 'Establishment of the Chinmaya Cultural Complex. Inaugurated by Pujya Sw. Tejomayanada ji.',
    type: 'complex',
    tag: 'Inauguration by Pujya Sw. Tejomayananda',
    km: 'KM 05',
    icon: 'Building2',
  },
  {
    id: 6,
    year: '2003',
    displayYear: '2003',
    title: 'Bridge at Shantamalleswara Temple',
    description: 'Construction of a bridge at the Shantamalleswara Temple.',
    type: 'infrastructure',
    tag: 'Bridge Infrastructure',
    km: 'KM 06',
    icon: 'Layers',
  },
  {
    id: 7,
    year: '2004',
    displayYear: '2004',
    title: 'Foot Path Bridge',
    description: 'Construction of foot path bridge at Sri Shantamalleswara Temple.',
    type: 'infrastructure',
    tag: 'Devotee Pathway',
    km: 'KM 07',
    icon: 'Navigation',
  },
  {
    id: 8,
    year: '2006',
    displayYear: '2006',
    title: 'Sri Chinmaya Sanjeevaraya Swami Temple',
    description: 'Construction of Sri Chinmaya Sanjeevaraya Swami Temple.',
    type: 'temple',
    tag: 'Temple Construction',
    km: 'KM 08',
    icon: 'Landmark',
  },
  {
    id: 9,
    year: '2014',
    displayYear: '2014',
    title: 'Kumbhabhishekam at Sri Chinmaya Sanjeevaraya Swami Temple',
    description: 'Kumbhabhishekam at Sri Chinmaya Sanjeevaraya Swami Temple.',
    type: 'spiritual',
    tag: 'Maha Kumbhabhishekam',
    km: 'KM 09',
    icon: 'Flame',
  },
  {
    id: 10,
    year: 'Every Summer',
    displayYear: 'Every Summer',
    title: 'Balavihar & Youth Camps',
    description: 'Every summer, Balavihar Camps for children and Youth Camps have been conducted to promote Indian culture, values and spiritual learning.',
    type: 'recurring',
    tag: 'Recurring Annual Programme',
    isRecurring: true,
    km: 'KM 10',
    icon: 'Sun',
  },
  {
    id: 11,
    year: '2019',
    displayYear: '2019',
    title: 'Chinmaya Vani',
    description: 'Chinmaya Vani inaugurated by Sw. Swaroopanandaji.',
    type: 'inauguration',
    tag: 'Inaugurated by Sw. Swaroopanandaji',
    km: 'KM 11',
    icon: 'Mic',
  },
  {
    id: 12,
    year: '2025',
    displayYear: '2025',
    title: 'Kumbhabhishekam at Sri Shantamalleswara Swami',
    description: 'Kumbhabhishekam at Sri Shantamalleswara Swami.',
    type: 'spiritual',
    tag: 'Maha Kumbhabhishekam',
    km: 'KM 12',
    icon: 'Flame',
  },
  {
    id: 13,
    year: '2025–26',
    displayYear: '2025–26',
    title: 'District-Level Chinmaya Geeta Chanting Competitions',
    description: 'The Mission conducted District-Level Chinmaya Geeta Chanting Competitions, continuing its long-standing commitment to value-based education and cultural activities.',
    type: 'continuing',
    tag: 'District Cultural Initiative',
    km: 'KM 13',
    icon: 'Trophy',
  },
];
