export const adoniInstitutionsList = [
  'Stonehill International School',
  'Stonehill EM High School',
  'Bhasyam Public School',
  'Narayana E-Techno School',
  'Sri Chaitanya School',
  'Chinmaya Vidyalaya',
  'Roots Global School (CBSE)',
  'Plaksha World of School',
  'Plaksha Kids World School',
  'Kiddys Global School',
  "Kiddy's High School",
  'Kiddys E-Techno School',
  "St. Joseph's High School",
  "St. Joseph's Convent",
  'Amaravati International School',
  'Narendra English Medium School',
  'Alfa English Medium School',
  'Mohammed Ali English Medium School',
  'National English Medium School',
  'National School',
  'Sri Sarada Niketan High School',
  'Milton Grammar English Medium High School',
  'Shelly English Medium High School',
  'Akshara Sree English Medium High School',
  'Emile Curriculum English Medium School',
  'Sri Vidya English Medium High School',
  'Sri Balaji Vidya Niketan',
  'Sri Balaji Vidyaniketan School',
  'Jawaher English Medium High School',
  'The Elahi English Medium School',
  'Annunya Juniors English Medium School',
  'Aruna Primary School',
  'Kidzee Preschool',
  'Makoons Play School',
  'Smartkidz Play School',
  'Sri Vidya Day and Residential High School',
  'Sri Jiheswara Vidyalaya',
  'Sanskriti Global Preschool - Adoni',
  'Mithram Nurture Preschool',
  'Little Angels Montessori School',
  'Times Primary School (Times.PS.EM.Adoni)',
  'Sri Chaitanya EM UP School',
  'Akshara Sree English Medium Primary School',
  'C. Mallikarjuna Vidyalayam',
  'Sri Vidya EM T.M. School',
  'Vivekananda Junior College Adoni',
  'Yale Malleshappa Kannada High School',
  'Shelley English Medium High School',
  'Bhasyam School',
  'Kiddiez Global School',
  'Sri Vidya High School',
];
